import type { Metadata } from "next";
import { Inter } from "next/font/google"
import {useLocale, useTranslations} from 'next-intl';
import "./globals.css";
import Navbar from "./components/Navbar";
import { cn } from "@/lib/utils"
import Footer from "./components/Footer";
import { locales } from "@/navigation";
import { ReactNode } from "react";
import { unstable_setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
 
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

type Props = {
  children: ReactNode;
  params: {locale: string};
};

export default function RootLayout({children, params}: Props) {
  unstable_setRequestLocale(params.locale);
  const locale = useLocale();

  if (params.locale !== locale) {
    notFound();
  }

  const t = useTranslations('navbar');
  
  return (
    <html lang={locale}>
      <body className={cn("min-h-screen bg-gray-100 font-sans antialiased", inter.variable)}>
        <Navbar 
          value={t('value')}
          real_estate={t('real_estate')}
          framework={t('framework')}
          contact={t('contact')}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
